# Basic Python modules for finance

-numpy
-pandas
-matplotlib
-math
-random
-statsmodels

## Arrays(by numpy)

In [5]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])

In [6]:
print(a)
print(b)

print(a.shape)
print(b.shape)

[[1 2 3]
 [4 5 6]]
[1 2 3]
(2, 3)
(3,)


In [7]:
a[0][0]


1

In [8]:
a[0]

array([1, 2, 3])

In [9]:
b[1]

2

## Generating Random Numbers

In [11]:
import random

In [12]:
prob = random.random()
print(prob)

0.8412792919712558


In [13]:
number = random.randint(1,10)
print(number)

3


In [14]:
import numpy as np
matrix = np.random.randint(1,10,(3,5))
print(matrix)

[[9 7 9 5 2]
 [4 6 2 6 6]
 [6 9 9 3 3]]
